; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_esp32c6]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino

; Serial Monitor Konfiguration
monitor_speed = 115200
; monitor_port = COM14  ; COM-Port manuell festlegen (z.B. COM3, COM4, etc.)
; monitor_port = /dev/ttyUSB0  ; Linux/Mac: /dev/ttyUSB0, /dev/ttyACM0, etc.

;Upload Port (optional, wird normalerweise automatisch erkannt)
;upload_port = COM4

; Partition Table
board_build.partitions = partitions.csv

; Filesystem (LittleFS für config.json)
board_build.filesystem = littlefs

; Test-Dateien aus Build ausschließen
; HINWEIS: build_src_filter funktioniert nicht mit ESP-IDF!
; Stattdessen wird src/CMakeLists.txt verwendet

; Build-Flag: UNIX-Timestamp zur Compile-Zeit (für NVS-Ring-Speicher-Version)
build_flags = 
;    -v
    -DBUILD_TIMESTAMP=$UNIX_TIME
    -DTEMPLATE_PLACEHOLDER=96  ; 96 = Backtick (ASCII) ==> ESPAsyncWebServer
;Für Testzwecke immer gleichen wert schreiben, damit NVS-Ring-Speicher nicht neu initialisiert wird:
;   -DBUILD_TIMESTAMP=1735228800
    
; Libraries
lib_compat_mode = strict
lib_ldf_mode = chain
lib_deps = 
    bblanchon/ArduinoJson@^7.4.2
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
    