; gas-o-meter2 platformio.ini – ARDUINO + ESP-IDF mit Src-Filter
[platformio]
default_envs = arduino

[env]
lib_deps = bblanchon/ArduinoJson@^7.4.2
lib_ldf_mode = chain

[env:arduino]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_compat_mode = strict
lib_deps = ${env.lib_deps}
    ESP32Async/AsyncTCP
    ESP32Async/ESPAsyncWebServer
build_flags = 
    -DTEMPLATE_PLACEHOLDER=96
    # BUILD_TIMESTAMP wird jetzt in version.h aus __DATE__ und __TIME__ berechnet
build_src_filter = +<main_arduino.cpp> -<main_idf.cpp>  ; NUR main_arduino.cpp

[env:espidf]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = seeed_xiao_esp32c6
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_build.filesystem = littlefs
lib_compat_mode = off
lib_deps = ${env.lib_deps}
build_flags = 
    -DTEMPLATE_PLACEHOLDER=96
    -DCONFIG_ESP_ULP_LP_CORE_ENABLE=y
    # BUILD_TIMESTAMP wird jetzt in version.h aus __DATE__ und __TIME__ berechnet
;build_src_filter = +<main_idf.cpp> -<main_arduino.cpp>  ; NUR main_idf.cpp ===> in CMakeLists.txt aufnhemen!
